/*
Introduction to Instana public APIs

Testing CustomDashboardsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package instana

import (
	openapiclient "./openapi"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_instana_CustomDashboardsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CustomDashboardsApiService AddCustomDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CustomDashboardsApi.AddCustomDashboard(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomDashboardsApiService DeleteCustomDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var customDashboardId string

		resp, httpRes, err := apiClient.CustomDashboardsApi.DeleteCustomDashboard(context.Background(), customDashboardId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomDashboardsApiService GetCustomDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var customDashboardId string

		resp, httpRes, err := apiClient.CustomDashboardsApi.GetCustomDashboard(context.Background(), customDashboardId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomDashboardsApiService GetCustomDashboards", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CustomDashboardsApi.GetCustomDashboards(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomDashboardsApiService GetShareableApiTokens", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CustomDashboardsApi.GetShareableApiTokens(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomDashboardsApiService GetShareableUsers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CustomDashboardsApi.GetShareableUsers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomDashboardsApiService UpdateCustomDashboard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var customDashboardId string

		resp, httpRes, err := apiClient.CustomDashboardsApi.UpdateCustomDashboard(context.Background(), customDashboardId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
