/*
Introduction to Instana public APIs

Testing SLIReportApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package instana

import (
	openapiclient "./openapi"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_instana_SLIReportApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SLIReportApiService GetSli", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sliId string

		resp, httpRes, err := apiClient.SLIReportApi.GetSli(context.Background(), sliId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
