/*
Introduction to Instana public APIs

Testing InfrastructureCatalogApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package instana

import (
	openapiclient "./openapi"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_instana_InfrastructureCatalogApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InfrastructureCatalogApiService GetInfrastructureCatalogMetrics", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var plugin string

		resp, httpRes, err := apiClient.InfrastructureCatalogApi.GetInfrastructureCatalogMetrics(context.Background(), plugin).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfrastructureCatalogApiService GetInfrastructureCatalogPlugins", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.InfrastructureCatalogApi.GetInfrastructureCatalogPlugins(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfrastructureCatalogApiService GetInfrastructureCatalogPluginsWithCustomMetrics", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.InfrastructureCatalogApi.GetInfrastructureCatalogPluginsWithCustomMetrics(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfrastructureCatalogApiService GetInfrastructureCatalogSearchFields", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.InfrastructureCatalogApi.GetInfrastructureCatalogSearchFields(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
