/*
Introduction to Instana public APIs

Testing InfrastructureTopologyApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package instana

import (
	openapiclient "./openapi"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_instana_InfrastructureTopologyApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InfrastructureTopologyApiService GetRelatedHosts", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var snapshotId string

		resp, httpRes, err := apiClient.InfrastructureTopologyApi.GetRelatedHosts(context.Background(), snapshotId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfrastructureTopologyApiService GetTopology", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.InfrastructureTopologyApi.GetTopology(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
